services:
  # PHP-FPM Service для Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: cloudsigma.com/php
    image: april_app_image:latest
    container_name: april_app
    restart: "always"
    tty: true
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    # environment:
    #   XDEBUG_MODE: debug
    #   XDEBUG_CONFIG: client_host=192.168.250.102 
    networks:
      - april_app-network
    depends_on:
      - redis
      - db
    ports:
     - "9000:9000"
    command: /bin/sh -c "php-fpm && sleep 20 && php artisan key:generate && php artisan migrate --force"
    # command: /bin/sh -c "php-fpm & php artisan websockets:serve"

    # Nginx Service


  # MySQL Service
  db:
    image: mysql:8.0
    container_name: april_app_db
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: cfdx # Задай свой пароль для root
      MYSQL_DATABASE: bitrixhook # Название базы данных
      MYSQL_USER: bitrixhook # Имя пользователя
      MYSQL_PASSWORD: Vadimsa1988! # Пароль пользователя
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - april_app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis_april_app
    restart: "unless-stopped"
    ports:
      # - "6379:6379"
      - "6380:6379"
    networks:
      - april_app-network

  queue-default:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: april_app_image:latest
    command: php /var/www/html/artisan queue:work redis --sleep=3 --tries=1
    volumes:
      - .:/var/www/html
    environment:
      - QUEUE_CONNECTION=redis
    user: 'www-data'
    networks:
      - april_app-network
    depends_on:
      - app
      - redis
      - db
    deploy:
      replicas: 1

  queue-low-priority:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: april_app_image:latest
    command: php /var/www/html/artisan queue:work redis --sleep=3 --tries=1 --queue=low-priority
    volumes:
      - .:/var/www/html
    environment:
      - QUEUE_CONNECTION=redis
    user: 'www-data'
    networks:
      - april_app-network
    depends_on:
      - app
      - redis
      - db
    deploy:
      replicas: 1

  queue-high-priority:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: april_app_image:latest
    command: php /var/www/html/artisan queue:work redis --sleep=3 --tries=1 --queue=high-priority
    volumes:
      - .:/var/www/html
    environment:
      - QUEUE_CONNECTION=redis
    user: 'www-data'
    networks:
      - april_app-network
    depends_on:
      - app
      - redis
      - db
    deploy:
      replicas: 2

volumes:
  db_data:


networks:
  april_app-network:
    name: april_app-network
    driver: bridge
